# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a31790a79c946c76cf232419a0ea906e"
name = "BM Insanity Dev"
handle = "bm-insanity-dev"
application_url = "https://susan-word-apply-minnesota.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "buildmatstaging.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_files,read_metaobjects,read_orders,read_products,read_themes,unauthenticated_read_checkouts,unauthenticated_read_content,unauthenticated_read_customer_tags,unauthenticated_read_customers,unauthenticated_read_product_listings,unauthenticated_read_product_tags,unauthenticated_read_selling_plans,unauthenticated_write_checkouts,unauthenticated_write_customers,write_content,write_customers,write_draft_orders,write_files,write_metaobjects,write_orders,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://susan-word-apply-minnesota.trycloudflare.com/auth/callback",
  "https://susan-word-apply-minnesota.trycloudflare.com/auth/shopify/callback",
  "https://susan-word-apply-minnesota.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[app_proxy]
url = "https://susan-word-apply-minnesota.trycloudflare.com/app/proxy"
subpath = "bmapp"
prefix = "apps"

[pos]
embedded = false
