# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cd5f35517b5f119a3f2166110eda635a"
name = "BM Insanity"
handle = "buildmat-app"
application_url = "https://bm-insanity.fly.dev/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "buildmatstaging.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_metaobjects,read_products,write_files,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://bm-insanity.fly.dev/auth/callback",
  "https://bm-insanity.fly.dev/auth/shopify/callback",
  "https://bm-insanity.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
