# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b32d95389dff1e07f175147fd41f1b93"
name = "product-builder-app"
handle = "product-builder-app-2"
application_url = "https://d2c5-2001-ee0-4b52-af10-49bc-41bd-e1bf-93fc.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devmegamenu.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_metaobjects,read_products,write_files,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://d2c5-2001-ee0-4b52-af10-49bc-41bd-e1bf-93fc.ngrok-free.app/auth/callback",
  "https://d2c5-2001-ee0-4b52-af10-49bc-41bd-e1bf-93fc.ngrok-free.app/auth/shopify/callback",
  "https://d2c5-2001-ee0-4b52-af10-49bc-41bd-e1bf-93fc.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
