# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92c567249760ebdd465718fd71b4fe55"
name = "Product Builder For Dev"
handle = "product-builder-for-dev"
application_url = "https://b763-2001-ee0-4b52-af10-8d0f-a926-f9d6-bb28.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devmegamenu.myshopify.com"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_metaobjects,read_products,write_files,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://b763-2001-ee0-4b52-af10-8d0f-a926-f9d6-bb28.ngrok-free.app/auth/callback",
  "https://b763-2001-ee0-4b52-af10-8d0f-a926-f9d6-bb28.ngrok-free.app/auth/shopify/callback",
  "https://b763-2001-ee0-4b52-af10-8d0f-a926-f9d6-bb28.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
